name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install numpy
    - run: sudo apt update
    - run: sudo apt install inotify-tools
    - run: inotifywait -mr /home/runner/work/symphony/symphony/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'optimizing-ci-builds'
    - run: touch starting_build_uses-checkout_10
    - run: rm starting_build_uses-checkout_10
    - uses: actions/checkout@master
    - run: touch starting_build_BuildtheDockerimage_11
    - run: rm starting_build_BuildtheDockerimage_11
    - name: Build the Docker image
      run: |
        docker login --username=${{ secrets.DOCKER_HUB_USER }} --password=${{ secrets.DOCKER_HUB_PWD }}
        docker build -t b3log/symphony:latest .
        docker push b3log/symphony
    - run: touch starting_finished_finished_8979874
      if: always()
    - run: rm starting_finished_finished_8979874
      if: always()
    - name: rat check
      if: always()
      run: |
         if [ -f /home/runner/work/symphony/symphony/target/rat.txt ]; then cat /home/runner/work/symphony/symphony/target/rat.txt; fi
    - name: Check script file exists and execute
      if: always()
      run: |
        [ -f .github/workflows/script.py ] && python .github/workflows/script.py
        [ -f /home/runner/work/symphony/symphony/optimizing-ci-builds-ci-analysis/job.csv ] || mkdir -p /home/runner/work/symphony/symphony/optimizing-ci-builds-ci-analysis/; echo "${GITHUB_RUN_ID},${GITHUB_JOB},symphony,${GITHUB_WORKFLOW}" > /home/runner/work/symphony/symphony/optimizing-ci-builds-ci-analysis/job.csv
    - name: Checkout to destination CI-analyzes repo
      uses: actions/checkout@v3
      if: always()
      with:
        path: symphony
        ref: '1687017076-548a464'
        repository: 'UT-SE-Research/ci-analyzes'
        token: '${{ secrets.API_TOKEN_GITHUB }}'
        persist-credentials: true
    - name: Copy files to push to another directory
      if: always()
      run: |
        mkdir -p symphony/symphony/.github/workflows/dockerimage/build
        cp -rvT optimizing-ci-builds-ci-analysis symphony/symphony/.github/workflows/dockerimage/build
    - run: echo https://github.com/UT-SE-Research/ci-analyzes/tree/1687017076-548a464/symphony/.github/workflows/dockerimage/build
    - name: Pushes analysis to another repository
      if: always()
      working-directory: symphony
      run: |
        commit_message=$GITHUB_REPOSITORY@$GITHUB_WORKFLOW_SHA
        git config --global user.name 'UT-SE-Research'
        git config --global user.email '${{ secrets.EMAIL }}'
        git add .
        git commit -m $commit_message
        while ! git push origin 1687017076-548a464; do
          git pull --rebase origin 1687017076-548a464
          sleep $((RANDOM % 5 + 1))
        done
